// Korean for every string the plugin shows; English is the key. The snippets themselves and
// the output they log are never translated. `tests/ko.test.ts` fails on a `t("…")` or an
// example title with no entry here, and on an entry nothing uses.
export const KO: Record<string, string> = {
  "1 type error; running anyway: {message}": "타입 오류 1개가 있지만 실행합니다: {message}",
  "A link opened a snippet in the API Playground. Replace the snippet in the editor? Its changes are not saved.": "링크가 API 플레이그라운드에서 스니펫을 열었습니다. 편집기의 스니펫을 바꿀까요? 저장하지 않은 변경 사항이 있습니다.",
  "A map tool: clear fog with a brush": "맵 도구: 브러시로 전장의 안개 걷기",
  "A name for the snippet:": "스니펫 이름:",
  "A panel built from widgets": "위젯으로 만든 패널",
  "Add a menu item and a hotkey": "메뉴 항목과 단축키 추가",
  "API Playground": "API 플레이그라운드",
  "API reference": "API 레퍼런스",
  "Ask, wait, then edit": "묻고, 기다린 다음 편집",
  "Author": "작성자",
  "Cancel": "취소",
  "Clear": "지우기",
  "Close": "닫기",
  "Compiling…": "컴파일 중…",
  "Copy a link that opens this snippet in the playground": "이 스니펫을 플레이그라운드에서 여는 링크 복사",
  "Copy Link": "링크 복사",
  "Ctrl+Enter runs the snippet.": "Ctrl+Enter로 스니펫을 실행합니다.",
  "Delete": "삭제",
  "Delete Snippet": "스니펫 삭제",
  "Delete the saved snippet “{name}”? The editor keeps its text.": "저장된 스니펫 “{name}”을(를) 삭제할까요? 편집기의 내용은 그대로 남습니다.",
  "Delete…": "삭제…",
  "Description": "설명",
  "Download the snippet as the files of a new plugin": "스니펫을 새 플러그인의 파일로 내려받기",
  "Draw over the map": "맵 위에 그리기",
  "Examples": "예제",
  "Export": "내보내기",
  "Export as Plugin": "플러그인으로 내보내기",
  "Export as Plugin…": "플러그인으로 내보내기…",
  "Id": "ID",
  "line {line}": "{line}번째 줄",
  "Link copied. It opens this snippet in the playground of whoever follows it; nothing runs until they press Run.": "링크를 복사했습니다. 링크를 연 사람의 플레이그라운드에 이 스니펫이 열리며, 실행을 누르기 전에는 아무것도 실행되지 않습니다.",
  "Listen to what the user does": "사용자의 동작 듣기",
  "Loading the code editor…": "코드 편집기를 불러오는 중…",
  "Name": "이름",
  "New snippet": "새 스니펫",
  "Not run: fix the syntax error first.": "실행하지 않았습니다. 먼저 구문 오류를 고치세요.",
  "Open an example or a saved snippet": "예제나 저장된 스니펫 열기",
  "Output": "출력",
  "Paint terrain as one undo step": "지형을 한 번의 실행 취소 단계로 칠하기",
  "Place units in a ring": "유닛을 원형으로 배치",
  "Ran in {ms} ms.": "{ms}ms 동안 실행했습니다.",
  "Ran in {ms} ms. Undo steps added: {count}.": "{ms}ms 동안 실행했습니다. 추가된 실행 취소 단계: {count}개.",
  "Read the open map": "열린 맵 읽기",
  "Replace": "바꾸기",
  "Run": "실행",
  "Run the snippet (Ctrl+Enter)": "스니펫 실행 (Ctrl+Enter)",
  "Running…": "실행 중…",
  "Save": "저장",
  "Save As": "다른 이름으로 저장",
  "Save As…": "다른 이름으로 저장…",
  "Save it, or use Export as Plugin to share it as files.": "저장하거나, 플러그인으로 내보내기로 파일을 만들어 공유하세요.",
  "Save the snippet (Ctrl+S)": "스니펫 저장 (Ctrl+S)",
  "Saved": "저장됨",
  "Saved {file}.": "{file}을(를) 저장했습니다.",
  "Saved “{name}”.": "“{name}”을(를) 저장했습니다.",
  "Show the line": "해당 줄 보기",
  "Stop": "중지",
  "Stopped: everything the last run registered has been taken back.": "중지했습니다. 마지막 실행이 등록한 것을 모두 되돌렸습니다.",
  "Take back everything the last run registered": "마지막 실행이 등록한 것을 모두 되돌리기",
  "The browser's storage for the editor is full.": "브라우저에서 편집기가 쓰는 저장 공간이 가득 찼습니다.",
  "The code editor could not be loaded: {error}": "코드 편집기를 불러오지 못했습니다: {error}",
  "The link may have been cut short when it was copied.": "복사하는 동안 링크가 잘렸을 수 있습니다.",
  "The link to this snippet:": "이 스니펫의 링크:",
  "The link's snippet could not be read": "링크의 스니펫을 읽지 못했습니다",
  "The run failed. What it registered before the error stays until Stop.": "실행에 실패했습니다. 오류 전에 등록한 것은 중지할 때까지 남아 있습니다.",
  "The snippet becomes the body of the plugin's activate(api) function. You get a zip with plugin.json, plugin.ts, and the package.json and tsconfig.json to type-check and build it. Its README says how to load it into the editor from your computer.": "스니펫은 플러그인의 activate(api) 함수 본문이 됩니다. plugin.json, plugin.ts와 타입 검사 및 빌드에 쓰는 package.json, tsconfig.json이 든 zip 파일을 받습니다. 내 컴퓨터에서 편집기로 불러오는 방법은 README에 있습니다.",
  "The snippet could not be compiled:": "스니펫을 컴파일하지 못했습니다:",
  "The snippet could not be saved": "스니펫을 저장하지 못했습니다",
  "The snippet in the editor has changes that are not saved. Replace it?": "편집기의 스니펫에 저장하지 않은 변경 사항이 있습니다. 바꿀까요?",
  "The snippet is too long for a link": "스니펫이 너무 길어 링크로 만들 수 없습니다",
  "This snippet came from a link. Read it before you run it: a snippet can do anything the editor can.": "이 스니펫은 링크로 열었습니다. 실행하기 전에 읽어 보세요. 스니펫은 편집기가 할 수 있는 일을 모두 할 수 있습니다.",
  "Try Again": "다시 시도",
  "Types from @scm-js/plugin-api {version}": "@scm-js/plugin-api {version}의 타입",
  "Undid the last run's map edits. Undo steps taken back: {count}.": "마지막 실행이 맵에 한 편집을 되돌렸습니다. 되돌린 실행 취소 단계: {count}개.",
  "Undo Run": "실행 되돌리기",
  "Undo the map edits the last run made": "마지막 실행이 맵에 한 편집을 실행 취소",
  "Undo the map edits the last run made (undo steps: {count})": "마지막 실행이 맵에 한 편집을 실행 취소 (실행 취소 단계: {count}개)",
  "Untitled": "제목 없음",
  "What the run registered stays until Stop or the next run.": "실행이 등록한 것은 중지하거나 다시 실행할 때까지 남아 있습니다.",
  "What the snippet logs with console.log appears here.": "스니펫이 console.log로 기록한 내용이 여기에 나타납니다.",
  "Write a trigger from text": "텍스트로 트리거 작성",
  "{count} type errors; running anyway. The first: {message}": "타입 오류 {count}개가 있지만 실행합니다. 첫 번째: {message}",
};
